# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nodo.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'nodo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nnodo.proto\"\x1d\n\rSaludoRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"!\n\x0eSaludoResponse\x12\x0f\n\x07mensaje\x18\x01 \x01(\t21\n\x04Nodo\x12)\n\x06Saludo\x12\x0e.SaludoRequest\x1a\x0f.SaludoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nodo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SALUDOREQUEST']._serialized_start=14
  _globals['_SALUDOREQUEST']._serialized_end=43
  _globals['_SALUDORESPONSE']._serialized_start=45
  _globals['_SALUDORESPONSE']._serialized_end=78
  _globals['_NODO']._serialized_start=80
  _globals['_NODO']._serialized_end=129
# @@protoc_insertion_point(module_scope)
